# Generated by Django 4.0 on 2021-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_following_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Following',
            field=models.IntegerField(null=True),
        ),
    ]
