# Generated by Django 4.0 on 2021-12-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follow',
            new_name='Following',
        ),
        migrations.AddField(
            model_name='user',
            name='Followers',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Follows',
        ),
    ]
