# Generated by Django 4.0 on 2021-12-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_liked_who_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_num',
            field=models.IntegerField(default=0),
        ),
    ]
