# Generated by Django 4.0 on 2021-12-29 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_user_following_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Followers',
        ),
        migrations.AddField(
            model_name='user',
            name='Followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
