# Generated by Django 4.0 on 2021-12-29 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_remove_user_following_num_remove_user_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='Following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
