# Generated by Django 4.0 on 2021-12-29 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Following',
        ),
        migrations.CreateModel(
            name='Follow_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followers', models.ManyToManyField(blank=True, related_name='Followers', to=settings.AUTH_USER_MODEL)),
                ('Following', models.ManyToManyField(blank=True, related_name='Following', to=settings.AUTH_USER_MODEL)),
                ('Person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.user')),
            ],
        ),
    ]
